In [17]:
a1 = [1,2,3,4,5,6]
a = 0
b = 0

for i in a1:
    if i%2==0:
        a = a+i
        print(a)
        continue
    if i%3==0:
        b = b+i
        print(b)
print(a,b)

2
3
6
12
12 3


In [24]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[5:9]

array([5, 6, 7, 8])

In [14]:
x[5::-3]

array([5, 2])

In [22]:
price = ['five','t','r','a']
price.add('5')
price

AttributeError: 'list' object has no attribute 'add'

In [32]:
n = [1,2,3,4]
len(n)

4

In [10]:
import numpy as np
A = ([1,2,3,4,5,6,7,8,9,10,11,12])
b = np.reshape(A, (3,4))
c = b[1:, 1:2]
d = np.array([1,2]).reshape(2,1)
print(c+d)

[[ 7]
 [12]]


In [12]:
a1 = ([1,2], [2,4], [4,5])
b = np.reshape(a1,(2,3))
print(b)

[[1 2 2]
 [4 4 5]]
