In [5]:
print("good", end="")
print("day")


goodday


In [4]:
result = 12-4 * (16//2**4) + 32
print(result)

40


In [3]:
print(5%11)

5


In [2]:
import numpy as np
c = np.arange(start = 1, stop = 7).reshape(2,3)
print(c)

[[1 2 3]
 [4 5 6]]


In [1]:
t1 = (1,2,'tuple',4)
t2 = (5,6,7)

In [2]:
t1.append(5)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
x = t2[t1[1]]

In [9]:
t3 = (list(t1),list(t2))

In [10]:
d1 = {1:"python",2:[1,2,3]}

In [5]:
d1[2].append(4)

NameError: name 'd1' is not defined

In [12]:
print(d1)

{1: 'python', 2: [1, 2, 3, 4]}


In [13]:
x=d1[0]

KeyError: 0

In [14]:
d1["one"]=1

In [15]:
print(d1)

{1: 'python', 2: [1, 2, 3, 4], 'one': 1}


In [18]:
d1.update({'one':2})
print(d1)

{1: 'python', 2: [1, 2, 3, 4], 'one': 2}


In [23]:
S1 = {1, 2, 3}
S2 = {5, 6, 3}
S1.add(4)
S2.add("4")
print(S1-S2)

{1, 2, 4}


In [38]:
S1 = 'Hello' 
S2 = 'World3'
print( S1[0:] + ' ' + S2[-2:])

Hello d3


In [2]:
import numpy as np
arr = np.array([[1, 9, 10], [3, 7, 6], [12, 8, 0]])
np.sum(arr, axis = 0)

array([16, 24, 16])

In [3]:
 np.sum([[1, 9, 10], [3, 7, 6], [12, 8, 0]])

56

In [4]:
 np.sum(arr, axis = 1)

array([20, 16, 20])

In [8]:
mat = np.matrix('5, 9, 10; 2, 5, 4; 1, 9, 8; 2, 6, 8')
mat1 = np.matrix('1, 2, 3, 4')
mat2 = np.insert(mat, 1, mat1, axis= 1)
print(mat2)

[[ 5  1  9 10]
 [ 2  2  5  4]
 [ 1  3  9  8]
 [ 2  4  6  8]]


In [10]:
student = {'name': 'Jane', 'age': 25, 'courses': ['Math', 'Statistics']}
student['phone'] = '123-456'
student.update({'age' : 26})
print(student)

{'name': 'Jane', 'age': 26, 'courses': ['Math', 'Statistics'], 'phone': '123-456'}


In [11]:
student.update({'age' : 26, 'phone': '123-456'})
print(student)

{'name': 'Jane', 'age': 26, 'courses': ['Math', 'Statistics'], 'phone': '123-456'}


In [12]:
c = np.arange(start = 1, stop = 20, step = 3)
print(c[5])

16


In [1]:
print( '$100 $200 $300'.count('$'), '$100 $200 $300'.count('$', 5, 10), '$100 $200 $300'.count('$', 5) )

3 1 2


In [2]:
print(12-4*(16//2**4)+32)

40


In [8]:
a = [1,2,3,4,5]
a.count(2)

1

In [1]:
a={1,2,[4,5,6]}
print(a)

TypeError: unhashable type: 'list'